### ISSUE TITLE
How to view the binary error matrices

### ISSUE THREAD

**Issue by tourist7f** [anindita127/Complextext2animation#7]
Hello,
I clone your code and evaluated the provided pre-trained model. It creates some binary file under the output folder.
I tried to open this file directly but it ends up showed me 
00000000: | 8004 | 95b9 | 0000 | 0000
-- | -- | -- | -- | --
00000008: | 0000 | 005d | 9428 | 473f
00000010: | c536 | 9c54 | 9828 | d147
00000018: | 3fee | 805b | c8ba | 1991
00000020: | 473f | edce | d5a6 | 0d73
00000028: | c447 | 3fef | 901c | 2203
00000030: | 4850 | 473f | ee6c | 8b79
00000038: | 636e | d247 | 3fed | 4bf8
00000040: | d76f | f42a | 473f | f29d
00000048: | e041 | 068f | 1447 | 3ff3
00000050: | e2bd | 8ba4 | edd1 | 473f
00000058: | eb73 | 730b | b4c5 | 3247
00000060: | 3ff1 | 5445 | aaa9 | 22d2
00000068: | 473f | f318 | 1078 | fbbc
00000070: | 6f47 | 3fec | 2c17 | 0383
00000078: | 93f6 | 473f | ed5e | 98be
00000080: | 695c | a047 | 3fea | c2c0
00000088: | 508f | 5c32 | 473f | ec79
00000090: | d4dd | 0839 | ea47 | 3fec
00000098: | 2928 | b0ed | cd54 | 473f
000000a0: | ee65 | 0df1 | 99fc | a347
000000a8: | 3fea | 4a1f | 2214 | 682d
000000b0: | 473f | eccd | 0959 | 8a42
000000b8: | 8947 | 3fe5 | 6e05 | 42f8
000000c0: | 3b98 | 652e

I think probably I open it in a wrong way, how  should I open the binary error matrices

**Comment by dwro0121** [comment]
I think you can modify `eval_APE.py`, `eval_AVE.py`, and `eval_CEE_SEE.py` files to print directly.
or you can also open the output bin file with python code.
