### ISSUE TITLE
About rendering the output files

### ISSUE THREAD

**Issue by zhuangzhuang000** [anindita127/Complextext2animation#8]
Hello,
I clone your code and evaluated the provided pre-trained model. When I run `python render.py -dataset KITMocap -path2data ../dataset/kit-mocap -feats_kind rifke -clean_render 0 -save_dir save/model/exp_124_cpk_2stream_h_model_nocurriculum_time_32` , encountered the error :

> The number of file is   0
> inside readNRender
> MovieWriter stderr:
> [h264_amf @ 0000013a3609de40] DLL amfrt64.dll failed to open
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> 
> Traceback (most recent call last):
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\animation.py", line 230, in saving
>     yield self
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\animation.py", line 1156, in save
>     writer.grab_frame(**savefig_kwargs)
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\animation.py", line 383, in grab_frame
>     self.fig.savefig(self._frame_sink(), format=self.frame_format,
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\figure.py", line 2180, in savefig
>     self.canvas.print_figure(fname, **kwargs)
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\backend_bases.py", line 2084, in print_figure
>     result = print_method(
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\backends\backend_agg.py", line 446, in print_raw
>     fh.write(renderer._renderer.buffer_rgba())
> OSError: [Errno 22] Invalid argument
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "render.py", line 72, in <module>
>     argparseNloop(render_all)
>   File "E:\Virtual_patient\code\Complextext2animation\Complextext2animation-main\Complextext2animation\src\argsUtils.py", line 147, in argparseNloop
>     loop(args, i)
>   File "render.py", line 67, in render_all
>     parallelRender(filenames, descriptions, outputs, skel, feats_kind, data)
>   File "E:\Virtual_patient\code\Complextext2animation\Complextext2animation-main\Complextext2animation\src\renderUtils.py", line 130, in parallelRender
>     readNrender(filenums[i], filenames[i], descriptions[i],
>   File "E:\Virtual_patient\code\Complextext2animation\Complextext2animation-main\Complextext2animation\src\renderUtils.py", line 78, in readNrender
>     render(xyz_data, skel, time, output, figsize, description)
>   File "E:\Virtual_patient\code\Complextext2animation\Complextext2animation-main\Complextext2animation\src\utils\kit_visualization.py", line 150, in render
>     render_animation([['skeleton', (1,1,1), [xyz_data], None, None, [30, -65]]],
>   File "E:\Virtual_patient\code\Complextext2animation\Complextext2animation-main\Complextext2animation\src\utils\visualization.py", line 305, in render_animation
>     anim.save(output, writer=writer)
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\animation.py", line 1156, in save
>     writer.grab_frame(**savefig_kwargs)
>   File "D:\anaconda3\envs\text2motion\lib\contextlib.py", line 131, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\animation.py", line 232, in saving
>     self.finish()
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\animation.py", line 367, in finish
>     self.cleanup()
>   File "D:\anaconda3\envs\text2motion\lib\site-packages\matplotlib\animation.py", line 410, in cleanup
>     raise subprocess.CalledProcessError(
> subprocess.CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '400x400', '-pix_fmt', 'rgba', '-r', '100', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-b', '1000k',
>  '-y', 'save/model/exp_124_cpk_2stream_h_model_nocurriculum_time_32/dev/videos/01721_rifke.mp4']' returned non-zero exit status 1.
> 

I successfully ran your code for step 1, 2, 3, 5, 6.

**Comment by anindita127** [comment]
Hi, seems like you have an error for an installed package. What is inside 'save/model/exp_124_cpk_2stream_h_model_nocurriculum_time_32'? Are the reconstructed files stored here?

**Comment by zhuangzhuang000** [comment]
In the 'save/model/exp_124_cpk_2stream_h_model_nocurriculum_time_32' are the results of step 5 (there are three dev,test,train folders with multiple xxx_rifke.csv) and the results of step 6 (four .bin files)

**Comment by zhuangzhuang000** [comment]
I have solved this problem. The problem is that the version of the ffmpeg encoder is different. I used NVIDIAGPU, guessed that the author used AMDGPU, and I modified line 267 of visualization.py from `writer = Writer(fps=fps, metadata={}, bitrate=bitrate)` to `writer = Writer(fps=fps, metadata={}, bitrate=bitrate, codec='h264_nvenc')`, it worked.
